server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Rutas del frontend (React Router / Vue Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy al backend — ajusta la IP/hostname según tu EC2
    location /api/ {
        proxy_pass http://<IP-PRIVADA-EC2-BACK>:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
